SELECT * FROM DICT;

SELECT TABLE_NAME
    FROM USER_TABLES;
    
SELECT OWNER, TABLE_NAME
    FROM ALL_TABLES;
    
SELECT * FROM USER_INDEXES;

SELECT * FROM USER_IND_COLUMNS;

--인덱스 생성
CREATE INDEX IDX_EMP_SAL
    ON EMP(SAL);
    
SELECT * FROM USER_IND_COLUMNS;

--인덱스 삭제
DROP INDEX IDX_EMP_SAL;

SELECT * FROM USER_IND_COLUMNS;

--뷰 생성
--부서 번호가 20인 사원의 사원번호, 사원 이름, 직책, 부서 번호 출력
CREATE VIEW VW_EMP20
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO
        FROM EMP
        WHERE DEPTNO = 20);
        
SELECT * FROM USER_VIEWS;

SELECT * FROM VW_EMP20;
--뷰 삭제
DROP VIEW VW_EMP20;

--인라인 뷰
SELECT ROWNUM, E.*
    FROM EMP E;
    
SELECT ROWNUM, E.*
    FROM EMP E
    ORDER BY SAL DESC;
    
--인라인 뷰 TOP N
--서브쿼리 이용
SELECT ROWNUM, E.*
    FROM (SELECT *
            FROM EMP E
            ORDER BY SAL DESC) E
    WHERE ROWNUM <= 3;
    
--WITH절 사용
WITH E AS (SELECT * FROM EMP ORDER BY SAL DESC)
SELECT ROWNUM, E.*
    FROM E
    WHERE ROWNUM <=3;
    
--시퀀스
CREATE TABLE DEPT_SEQUENCE
    AS SELECT *
        FROM DEPT
        WHERE 1<>1;

SELECT * FROM DEPT_SEQUENCE;

CREATE SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 10
    START WITH 10
    MAXVALUE 90
    MINVALUE 0
    NOCYCLE
    CACHE 2;
    
SELECT * FROM USER_SEQUENCES;

--시퀀스 사용
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
    VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');

SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--가장 마지막으로 생성된 시퀀스 확인
SELECT SEQ_DEPT_SEQUENCE.CURRVAL
    FROM DUAL;
    
--시퀀스에서 생성한 순번을 반복 사용하여 INSERT문 실행
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
    VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');
    
SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--시퀀스 수정
ALTER SEQUENCE SEQ_DEPT_SEQUENCE
    INCREMENT BY 3
    MAXVALUE 99
    CYCLE;
    
INSERT INTO DEPT_SEQUENCE (DEPTNO, DNAME, LOC)
    VALUES(SEQ_DEPT_SEQUENCE.NEXTVAL, 'DATABASE', 'SEOUL');
    
SELECT * FROM DEPT_SEQUENCE ORDER BY DEPTNO;

--시퀀스 삭제
DROP SEQUENCE SEQ_DEPT_SEQUENCE;

SELECT * FROM USER_SEQUENCES;

--동의어 생성
CREATE SYNONYM E
    FOR EMP;

SELECT * FROM E;

--동의어 삭제
DROP SYNONYM E;