--Q1
CREATE TABLE EMPIDX
    AS SELECT * FROM EMP;
            
CREATE INDEX IDX_EMPIDX_EMPNO
    ON EMPIDX(EMPNO);
    
SELECT * FROM USER_IND_COLUMNS;

--Q2
CREATE VIEW EMPIDX_OVER15K
    AS (SELECT EMPNO, ENAME, JOB, DEPTNO, SAL, NVL2(COMM, 'O', 'X') AS COMM 
        FROM EMP
        WHERE SAL > 1500);
        
SELECT * FROM EMPIDX_OVER15K;

--Q3
CREATE TABLE DEPTSEQ
    AS SELECT * FROM DEPT;
    
CREATE SEQUENCE SEQ_DEPT
    INCREMENT BY 1
    START WITH 1
    MAXVALUE 99
    MINVALUE 1
    NOCYCLE
    NOCACHE;

INSERT INTO DEPTSEQ
    VALUES(SEQ_DEPT.NEXTVAL, 'DATABASE', 'SEOUL');
    
INSERT INTO DEPTSEQ
    VALUES(SEQ_DEPT.NEXTVAL, 'WEB', 'BUSAN');
    
INSERT INTO DEPTSEQ
    VALUES(SEQ_DEPT.NEXTVAL, 'MOBILE', 'ILSAN');

SELECT * FROM DEPTSEQ;