--Q1
SELECT D.DEPTNO,
    D.DNAME, E.EMPNO, E.SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO 
    AND SAL > 2000
    ORDER BY D.DEPTNO, E.EMPNO;
    
SELECT DEPTNO,
    D.DNAME, E.EMPNO, E.SAL
    FROM EMP E JOIN DEPT D USING (DEPTNO)
    WHERE SAL > 2000
    ORDER BY DEPTNO, E.EMPNO;
    
--Q2
SELECT 
    D.DEPTNO, D.DNAME,
    TRUNC(AVG(SAL)) AS AVG_SAL,
    TRUNC(MAX(SAL)) AS MAX_SAL,
    TRUNC(MIN(SAL)) AS MIN_SAL,
    COUNT(SAL) AS CNT
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    GROUP BY D.DEPTNO, D.DNAME;
    
SELECT 
    D.DEPTNO, D.DNAME,
    TRUNC(AVG(E.SAL)) AS AVG_SAL,
    TRUNC(MAX(E.SAL)) AS MAX_SAL,
    TRUNC(MIN(E.SAL)) AS MIN_SAL,
    COUNT(E.SAL) AS CNT
    FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    GROUP BY D.DEPTNO, D.DNAME;
    
--Q3
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
    FROM EMP E, DEPT D
    WHERE E.DEPTNO(+) = D.DEPTNO;
    
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.JOB, E.SAL
    FROM EMP E RIGHT OUTER JOIN DEPT D ON (D.DEPTNO = E.DEPTNO);
    
--Q4
SELECT D.DEPTNO, D.DNAME, E1.EMPNO, E1.ENAME, E1.MGR, E1.SAL,
    E1.DEPTNO, S.LOSAL, S.HISAL, S.GRADE,
    E2.EMPNO AS MGR_EMPNO,
    E2.ENAME AS MGR_ENAME
    FROM EMP E1, EMP E2, DEPT D, SALGRADE S
    WHERE E1.DEPTNO(+) = D.DEPTNO
    AND E1.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
    AND E1.MGR = E2.EMPNO(+)
    ORDER BY D.DEPTNO, D.DNAME, E1.EMPNO;
    
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, 
    E.DEPTNO, S.LOSAL, S.HISAL, S.GRADE,
    E2.EMPNO AS MGR_EMPNO, 
    E2.ENAME AS MGR_ENAME
    FROM EMP E 
    RIGHT OUTER JOIN DEPT D
        ON (E.DEPTNO = D.DEPTNO)
    LEFT OUTER JOIN SALGRADE S
        ON (E.SAL BETWEEN S.LOSAL AND S.HISAL)
    LEFT OUTER JOIN EMP E2
        ON (E.MGR = E2.EMPNO)
    ORDER BY D.DEPTNO, E.EMPNO; 

