--DEPT 테이블을 복사해서 DEPT_TCL 만들기
CREATE TABLE DEPT_TCL
    AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE DNAME= 'RESEARCH';
SELECT * FROM DEPT_TCL;

ROLLBACK;

--트랜잭션을 영원히 반영하고 싶을 때는 COMMIT
INSERT INTO DEPT_TCL VALUES(50, 'DATABASE', 'SEOUL');
UPDATE DEPT_TCL SET LOC = 'BUSAN' WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE DNAME= 'RESEARCH';
SELECT * FROM DEPT_TCL;
COMMIT;

ROLLBACK;