--EMP와 같은 테이블 생성하기
CREATE TABLE EMP_DDL(
    EMPNO       NUMBER(4),
    ENAME       VARCHAR2(10),
    JOB         VARCHAR2(9),
    MGR         NUMBER(4),
    HIREDATE    DATE,
    SAL         NUMBER(7,2),
    COMM        NUMBER(7,2),
    DEPTNO      NUMBER(2)
);
DESC EMP_DDL;

--다른 테이블 복사하여 테이블 생성하기
CREATE TABLE DEPT_DDL
    AS SELECT * FROM DEPT;
DESC DEPT_DDL;

--다른 테이블의 일부를 복사하여 테이블 생성하기
CREATE TABLE EMP_DDL_30
    AS SELECT * FROM EMP
    WHERE DEPTNO = 30;
SELECT * FROM EMP_DDL_30;

--기존 테이블의 열 구조만 복사하여 새 테이블 생성하기
CREATE TABLE EMPDEPT_DDL
    AS SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE,
            E.SAL, E.COMM, D.DEPTNO, D.DNAME, D.LOC
        FROM EMP E, DEPT D
        WHERE 1 <> 1;
        
SELECT * FROM EMPDEPT_DDL;

--ALTER 예제
CREATE TABLE EMP_ALTER
    AS SELECT * FROM EMP;
    
ALTER TABLE EMP_ALTER
    ADD HP VARCHAR2(20);

SELECT * FROM EMP_ALTER;

--열이름 변경 RENAME
ALTER TABLE EMP_ALTER
    RENAME COLUMN HP TO TEL;
    
--열의 자료형 변경 MODIFY
ALTER TABLE EMP_ALTER
    MODIFY EMPNO NUMBER(5);
    
--열 삭제 DROP
ALTER TABLE EMP_ALTER
    DROP COLUMN TEL;
    
--테이블 이름 변경 RENAME
RENAME EMP_ALTER TO EMP_RENAME;
DESC EMP_RENAME;

--테이블 데이터 삭제 TRUNCATE
TRUNCATE TABLE EMP_RENAME;
SELECT * FROM EMP_RENAME;

--테이블 삭제 DROP
DROP TABLE EMP_RENAME;