--Q1
SELECT DEPTNO,
    TRUNC(AVG(SAL)) AS AVG_SAL,
    TRUNC(MAX(SAL)) AS MAX_SAL,
    TRUNC(MIN(SAL)) AS MIN_SAL,
    COUNT(SAL) AS CNT
    FROM EMP
    GROUP BY DEPTNO;
    
--Q2
SELECT JOB,
    COUNT(JOB)
    FROM EMP
    GROUP BY JOB
    HAVING COUNT(*) >= 3;
    
--Q3
SELECT 
    TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
    DEPTNO,
    COUNT(DEPTNO) AS CNT
    FROM EMP
    GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO;
    
--Q4
SELECT 
    NVL2(COMM, 'O', 'X') AS EXIST_COMM,
    COUNT(*) AS CNT
    FROM EMP
    GROUP BY NVL2(COMM, 'O', 'X');
    
--Q5
SELECT 
    DEPTNO,
    TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
    COUNT(*) AS CNT,
    MAX(SAL) AS MAX_SAL,
    SUM(SAL) AS SUM_SAL,
    AVG(SAL) AS AVG_SAL
    FROM EMP
    GROUP BY ROLLUP(DEPTNO, TO_CHAR(HIREDATE, 'YYYY')); 