--대, 소문자를 바꿔 주는 함수
SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
    FROM EMP;
    
--사원 이름이 SCOTT인 데이터 찾기
SELECT *
    FROM EMP
    WHERE UPPER(ENAME) = UPPER('scott');
    
--사원 이름의 SCOTT가 포함인 데이터 찾기
SELECT *
    FROM EMP
    WHERE UPPER(ENAME) LIKE UPPER('%scott%');
    
--사원 이름의 길이가 5 이상인 행 출력
SELECT ENAME, LENGTH(ENAME) 
    FROM EMP
    WHERE LENGTH(ENAME) >= 5;
    
--LENGTHB는 바이트의 수 반환
SELECT LENGTH('한글'), LENGTHB('한글')
    FROM DUAL;
    
--문자열 일부 추출 SUBSTR
SELECT JOB, SUBSTR(JOB,1,2), SUBSTR(JOB,3,2), SUBSTR(JOB,5)
    FROM EMP;
    
--SUBSTR 응용
SELECT JOB,
    SUBSTR(JOB,-LENGTH(JOB)),
    SUBSTR(JOB,-LENGTH(JOB),2),
    SUBSTR(JOB,-3)
    FROM EMP;
    
--문자열 데이터 안에서 특정 문자 위치 찾는 INSTR
SELECT INSTR('HELLO, ORACLE','L'),
       INSTR('HELLO, ORACLE','L',5),
       INSTR('HELLO, ORACLE','L',2,2)
       FROM DUAL;
       
--LIKE와 비슷하게 INSTR 응용
SELECT * FROM EMP
    WHERE INSTR(ENAME,'S') > 0;
    
--특정 문자를 다른 문자로 바꾸는 REPLACE
SELECT '010-2427-2487' AS REPLACE_BEFORE,
    REPLACE('010-2427-2487','-',' ') AS REPLACE_1,
    REPLACE('010-2427-2487','-') AS REPLACE_2
    FROM DUAL;
    
--데이터의 빈 공간을 특정 문자로 채우는 LPAD, RPAD
SELECT 'Oracle',
    LPAD('Oracle',10,'*') AS LPAD_1,
    RPAD('Oracle',10,'*') AS RPAD_1,
    LPAD('Oracle',10) AS LPAD_2,
    RPAD('Oracle',10) AS RPAD_2
    FROM DUAL;
    
--개인정보 뒷자리 가리기
SELECT
    RPAD('950306-',14,'*') AS JMNO,
    RPAD('010-2427-',13,'*') AS PHONE
    FROM DUAL;
    
--두 문자열 데이터를 합치는 CONCAT
SELECT
    CONCAT(EMPNO, ENAME),
    CONCAT(EMPNO, CONCAT(' : ', ENAME))
    FROM EMP
    WHERE ENAME = 'SCOTT';
    
SELECT
    EMPNO || ENAME,
    EMPNO || ' : ' || ENAME
    FROM EMP
    WHERE ENAME = 'SCOTT';
    
--특정 문자를 지우는 함수들


--반올림 함수 ROUND
SELECT 
    ROUND(1234.5678) AS ROUND,
    ROUND(1234.5678, 0) AS ROUND_0,
    ROUND(1234.5678, 1) AS ROUND_1,
    ROUND(1234.5678, 2) AS ROUND_2,
    ROUND(1234.5678, -1) AS ROUND_MINUS1,
    ROUND(1234.5678, -2) AS ROUND_MINUS2
    FROM DUAL;
    
--버림 함수 TRUNC
SELECT 
    TRUNC(1234.5678) AS TRUNC,
    TRUNC(1234.5678, 0) AS TRUNC_0,
    TRUNC(1234.5678, 1) AS TRUNC_1,
    TRUNC(1234.5678, 2) AS TRUNC_2,
    TRUNC(1234.5678, -1) AS TRUNC_MINUS1,
    TRUNC(1234.5678, -2) AS TRUNC_MINUS2
    FROM DUAL;
    
--지정한 숫자와 가까운 정수를 찾는 함수 CEIL, FLOOR
--CEIL은 큰 정수, FLOOR은 작은 정수
SELECT 
    CEIL(3.14),
    FLOOR(3.14),
    CEIL(-3.14),
    FLOOR(-3.14)
    FROM DUAL;

--숫자를 나눈 나머지 값을 구하는 함수 MOD
SELECT
    MOD(15, 6),
    MOD(10, 2),
    MOD(11, 2)
    FROM DUAL;


--날짜 데이터를 다루는 날짜 함수 SYSDATE
SELECT 
    SYSDATE AS NOW,
    SYSDATE-1 AS YESTERDAY,
    SYSDATE+1 AS TOMORROW
    FROM DUAL;

--몇 개월 이후 날짜를 구하는 함수 ADD_MONTHS
SELECT
    SYSDATE,
    ADD_MONTHS(SYSDATE, 3) AS THREE_MONTHS_LATER
    FROM DUAL;

--입사 10주년 되는 사원 데이터 추출
SELECT EMPNO, ENAME, HIREDATE,
    ADD_MONTHS(HIREDATE, 120) AS WORK10YEAR
    FROM EMP;

--두 날짜 간의 개월 수 차이를 구하는 함수 MONTHS_BETWEEN
SELECT EMPNO, ENAME, HIREDATE, SYSDATE,
    MONTHS_BETWEEN(HIREDATE, SYSDATE) AS MONTHS1,
    MONTHS_BETWEEN(SYSDATE, HIREDATE) AS MONTHS2,
    TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) AS MONTHS3
    FROM EMP;

--돌아오는 요일을 구하는 함수 NEXT_DAY
SELECT SYSDATE,
    NEXT_DAY(SYSDATE, '월요일')
    FROM DUAL;

--달의 마지막 날을 구하는 함수 LAST_DAY
SELECT SYSDATE,
    LAST_DAY(SYSDATE)
    FROM DUAL;

--날짜, 숫자 데이터를 문자 데이터로 변화하는 함수 TO_CHAR
SELECT
    SYSDATE,
    TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS 현재날짜시간
    FROM DUAL;

--월과 요일을 다양한 형식으로 출력하기
SELECT SYSDATE,
    TO_CHAR(SYSDATE, 'MM') AS MM,
    TO_CHAR(SYSDATE, 'MON') AS MON,
    TO_CHAR(SYSDATE, 'MONTH') AS MONTH,
    TO_CHAR(SYSDATE, 'DD') AS DD,
    TO_CHAR(SYSDATE, 'DY') AS DY,
    TO_CHAR(SYSDATE, 'DAY') AS DAY
    FROM DUAL;

--여러 언어로 날짜(월) 출력하기
SELECT SYSDATE,
    TO_CHAR(SYSDATE, 'MM') AS MM,
    TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = KOREAN' ) AS MON_KOR,
    TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = JAPANESE' ) AS MON_JPN,
    TO_CHAR(SYSDATE, 'MON', 'NLS_DATE_LANGUAGE = ENGLISH' ) AS MON_ENGLISH,
    TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = KOREAN' ) AS MONTH_KOR,
    TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = JAPANESE' ) AS MONTH_JPN,
    TO_CHAR(SYSDATE, 'MONTH', 'NLS_DATE_LANGUAGE = ENGLISH' ) AS MONTH_ENGLISH
    FROM DUAL;
    
--여러 언어로 날짜(요일) 출력하기
SELECT SYSDATE,
    TO_CHAR(SYSDATE, 'MM') AS MM,
    TO_CHAR(SYSDATE, 'DD') AS DD,
    TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE = KOREAN' ) AS DY_KOR,
    TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE = JAPANESE' ) AS DY_JPN,
    TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE = ENGLISH' ) AS DY_ENGLISH,
    TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE = KOREAN' ) AS DAY_KOR,
    TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE = JAPANESE' ) AS DAY_JPN,
    TO_CHAR(SYSDATE, 'DAY', 'NLS_DATE_LANGUAGE = ENGLISH' ) AS DAY_ENGLISH
    FROM DUAL;

--시간 형식 지정하여 출력
SELECT SYSDATE,
    TO_CHAR(SYSDATE, 'HH24:MI:SS') AS HH24MISS,
    TO_CHAR(SYSDATE, 'HH12:MI:SS AM') AS HH12MISS_AM,
    TO_CHAR(SYSDATE, 'HH:MI:SS P.M.') AS HHMISS_PM
    FROM DUAL;

--여러 가지 숫자 형식을 사용하여 급여 출력하기
SELECT SAL,
    TO_CHAR(SAL, '$999,999') AS SAL_$,
    TO_CHAR(SAL, 'L999,999') AS SAL_L,
    TO_CHAR(SAL, '999,999.00') AS SAL_1,
    TO_CHAR(SAL, '000,999,999.00') AS SAL_2,
    TO_CHAR(SAL, '000999999.99') AS SAL_3,
    TO_CHAR(SAL, '999,999,00') AS SAL_4
    FROM EMP;

--문자 데이터를 숫자 데이터로 변환하는 함수 TO_NUMBER
SELECT TO_NUMBER('1,300', '999,999') - TO_NUMBER('1,100', '999,999')
    FROM DUAL;

--문자 데이터를 날짜 데이터로 변화하는 함수 TO_DATE
SELECT 
    TO_DATE('2021-06-29', 'YYYY-MM-DD') AS TODATE1,
    TO_DATE('20210629', 'YYYY-MM-DD') AS TODATE2
    FROM DUAL;

--1981년 6월 1일 이후에 입사한 사원 정보 출력
SELECT * FROM EMP
    WHERE HIREDATE > TO_DATE('1981-06-01', 'YYYY/MM/DD');
    
--NULL 처리함수 NVL
SELECT EMPNO, ENAME, SAL, COMM, SAL+COMM,
    NVL(COMM, 0),
    SAL+NVL(COMM, 0)
    FROM EMP;

SELECT EMPNO, ENAME, COMM,
    NVL2(COMM, 'O', 'X'),
    SAL+NVL2(COMM, SAL*12+COMM, SAL*12) AS ANNSAL
    FROM EMP;    

--상황에 따라 다른 데이터를 반환하는 함수 DECODE, CASE
SELECT EMPNO, ENAME, JOB, SAL,
    DECODE(JOB,
            'MANAGER', SAL*1.1,
            'SALESMAN', SAL*1.05,
            'ANALYST', SAL,
            SAL*1.03) AS UPSAL
    FROM EMP;

SELECT EMPNO, ENAME, JOB, SAL,
    CASE JOB
        WHEN 'MANAGER' THEN SAL*1.1
        WHEN 'SALESMAN' THEN SAL*1.05
        WHEN 'ANALYST' THEN SAL
        ELSE SAL*1.03
    END AS UPSAL
    FROM EMP;