--합계를 구하는 SUM 함수
SELECT SUM(COMM)
    FROM EMP;
    
SELECT 
    SUM(DISTINCT SAL),
    SUM(ALL SAL),
    SUM(SAL)
    FROM EMP;
    
--데이터 개수를 구해 주는 COUNT 함수
SELECT COUNT(*)
    FROM EMP;
    
--30번 부서에 근무하는 직원 수 구하기
SELECT COUNT(*)
    FROM EMP
    WHERE DEPTNO = 30;
    
SELECT
    COUNT(DISTINCT SAL),
    COUNT(ALL SAL),
    COUNT(SAL)
    FROM EMP;
    
--최댓값과 최솟값을 구하는 MAX, MIN 함수
SELECT MAX(SAL)
    FROM EMP
    WHERE DEPTNO = 30;
    
SELECT MIN(SAL)
    FROM EMP
    WHERE DEPTNO = 30;

--제일 최근 입사일 구하기
SELECT MAX(HIREDATE)
    FROM EMP
    WHERE DEPTNO = 30;
    
--제일 오래된 입사일 출력하기
SELECT MIN(HIREDATE)
    FROM EMP
    WHERE DEPTNO = 30;
    
--평균 값을 구하는 AVG 함수
SELECT AVG(SAL)
    FROM EMP
    WHERE DEPTNO = 30;
    
SELECT AVG(DISTINCT SAL)
    FROM EMP
    WHERE DEPTNO = 30;
    
--결과 값을 원하는 열로 묶어 출력하는 함수 GROUP BY    
SELECT AVG(SAL), DEPTNO
    FROM EMP
    GROUP BY DEPTNO;
    
SELECT DEPTNO, JOB, AVG(SAL)
    FROM EMP
    GROUP BY DEPTNO, JOB
    ORDER BY DEPTNO, JOB;
    
--GROUP BY에 조건을 줄때 사용하는 함수 HAVING
SELECT DEPTNO, JOB, AVG(SAL)
    FROM EMP
    GROUP BY DEPTNO, JOB
        HAVING AVG(SAL) >= 2000
    ORDER BY DEPTNO, JOB;
    
--그룹화와 관련된 함수들
SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL)
    FROM EMP
    GROUP BY DEPTNO, JOB
    ORDER BY DEPTNO, JOB;
    
SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL)
    FROM EMP
    GROUP BY ROLLUP(DEPTNO, JOB);
    
SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL)
    FROM EMP
    GROUP BY CUBE(DEPTNO, JOB)
    ORDER BY DEPTNO, JOB;
    
SELECT DEPTNO, JOB, COUNT(*)
    FROM EMP
    GROUP BY DEPTNO, ROLLUP(JOB);
    
SELECT DEPTNO, JOB, COUNT(*)
    FROM EMP
    GROUP BY JOB, ROLLUP(DEPTNO);
    
SELECT DEPTNO, JOB, COUNT(*)
    FROM EMP
    GROUP BY GROUPING SETS(DEPTNO, JOB)
    ORDER BY DEPTNO, JOB;

--그룹화 함수 GROUPING 함수   
SELECT DEPTNO, JOB, COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL),
    GROUPING(DEPTNO),
    GROUPING(JOB)
    FROM EMP
    GROUP BY CUBE(DEPTNO, JOB)
    ORDER BY DEPTNO, JOB;
    
SELECT 
    DECODE(GROUPING(DEPTNO), 1, 'ALL_DEPT', DEPTNO) AS DEPTNO,
    DECODE(GROUPING(JOB), 1, 'ALL_JOB', JOB) AS JOB,
    COUNT(*), MAX(SAL), SUM(SAL), AVG(SAL)
    FROM EMP
    GROUP BY CUBE(DEPTNO, JOB)
    ORDER BY DEPTNO, JOB;
    
--그룹화 함수 GROUPING_ID
SELECT DEPTNO, JOB, COUNT(*), SUM(SAL),
    GROUPING(DEPTNO),
    GROUPING(JOB),
    GROUPING_ID(DEPTNO, JOB)
    FROM EMP
    GROUP BY CUBE(DEPTNO, JOB)
    ORDER BY DEPTNO, JOB;

--LISTAGG 함수
SELECT DEPTNO, ENAME
    FROM EMP
    GROUP BY DEPTNO, ENAME;
    
SELECT DEPTNO,
    LISTAGG(ENAME, ', ')
    WITHIN GROUP(ORDER BY SAL DESC) AS ENAMES
    FROM EMP
    GROUP BY DEPTNO;
    
--PIVOT, UNPIVOT 함수
SELECT *
    FROM(SELECT DEPTNO, JOB, SAL FROM EMP)
    PIVOT(MAX(SAL)
            FOR DEPTNO IN (10, 20, 30) )
    ORDER BY JOB;

SELECT *
    FROM(SELECT DEPTNO, JOB, SAL FROM EMP)
    PIVOT(MAX(SAL)
            FOR JOB IN 
            ('CLERK' AS CLERK,
             'SALESMAN' AS SALESMAN,
             'PRESIDENT' AS PRESIDENT,
             'MANAGER' AS MANAGER,
             'ANALYST' AS ANALYST))
    ORDER BY DEPTNO;